### ISSUE TITLE
Support Solaris

### ISSUE THREAD

**Issue by pioto** [pioto/Unix-Uptime#10]
See: https://rt.cpan.org/Ticket/Display.html?id=64001

---

Looks like we just need to parse the output of `kstat`:

module: unix
instance: 0
name: system_misc
class: misc
boot_time, avenrun_1min, avenrun_5min, avenrun_15min

sample command:

  `kstat -p unix:0:system_misc:boot_time`

yields:

  "unix:0:system_misc:boot_time\t1292560376"

Other stuff to look at, code-wise:

  http://www.brendangregg.com/K9Toolkit/uptime
  Sun::Solaris::Kstat (included on solaris, not on CPAN)

---

Apparently dividing the load average numbers by 256 gives the real value. 
Where this magic constant comes from, I have no idea.

**Comment by iynehz** [comment]
@pioto 
We need the support for Solaris. For that magic number of 256, I dont know too much either. But as you know /usr/bin/kstat uses Sun::Solaris::Kstat so that is an "official" magic number so we are safe to use it. 

Also see https://github.com/jrgp/linfo/blob/master/src/Linfo/OS/SunOS.php That one also uses the kstat cmd.

**Comment by pioto** [comment]
I don't have a Solaris system to test against, but patches are welcome.
